# Generated by Django 5.0.6 on 2024-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_email', models.CharField(max_length=100)),
                ('dr_specialization', models.CharField(max_length=100)),
                ('dr_appoinments', models.CharField(max_length=100)),
                ('dr_price', models.IntegerField()),
            ],
        ),
    ]
