# Generated by Django 5.0.6 on 2024-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100)),
                ('password_user', models.CharField(max_length=100)),
                ('accept_user', models.BooleanField(default=False)),
            ],
        ),
    ]
