# Generated by Django 5.0.6 on 2024-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0004_appointment_schedule_doctors_dr_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(default='000-000-0000', max_length=100),
            preserve_default=False,
        ),
    ]
