# Generated by Django 5.0.6 on 2024-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0006_registerusers_phone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='dr_address',
            field=models.CharField(default='damitta', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='dr_desc',
            field=models.TextField(default='yes he is a favourite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='dr_phone',
            field=models.CharField(default=1200474419, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='dr_topics',
            field=models.CharField(default='Periodontal surgery', max_length=100),
            preserve_default=False,
        ),
    ]
