# Generated by Django 5.0.6 on 2024-06-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0007_doctors_dr_address_doctors_dr_desc_doctors_dr_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='dr_img',
            field=models.ImageField(default='pics/im3.jpg', upload_to='pics'),
            preserve_default=False,
        ),
    ]
