# Generated by Django 5.0.6 on 2024-06-14 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0008_doctors_dr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dr_dates',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
    ]
