# Generated by Django 5.0.6 on 2024-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0009_schedule_dr_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dr_name',
            field=models.CharField(default='Dina', max_length=100),
            preserve_default=False,
        ),
    ]
