# Generated by Django 5.0.6 on 2024-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0010_schedule_dr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='Dina', max_length=100),
            preserve_default=False,
        ),
    ]
