# Generated by Django 5.0.6 on 2024-06-14 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0011_appointment_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoint_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
    ]
