# Generated by Django 5.0.6 on 2024-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteteeth', '0012_appointment_appoint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_name', models.FileField(upload_to='patient_files/')),
                ('patient_name', models.CharField(max_length=100)),
            ],
        ),
    ]
