# # Generated by Django 5.0.3 on 2024-03-27 20:08

# import datetime
# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('chat', '0003_account'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='dentist',
#             name='user',
#             field=models.ForeignKey(default=datetime.datetime(2024, 3, 27, 20, 8, 37, 88266, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='message',
#             name='created_by',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='message',
#             name='send_to',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='chat.dentist'),
#         ),
#     ]
# Generated by Django 5.0.3 on 2024-03-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="send_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_message",
                to="chat.dentist",
            ),
        ),
    ]
