# Generated by Django 5.0.3 on 2024-03-31 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_dentist_user_alter_message_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='name',
        ),
        migrations.AlterField(
            model_name='dentist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dentist', to=settings.AUTH_USER_MODEL),
        ),
    ]
